/*
api.emaildetective.io API

Testing EmailInfoAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package emaildetective

import (
	"context"
	"testing"

	openapiclient "github.com/AndrewCopeland/go-emaildetective"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_emaildetective_EmailInfoAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailInfoAPIService GetBulkEmailAddressInfo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailInfoAPI.GetBulkEmailAddressInfo(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailInfoAPIService GetEmailAddressInfo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var emailAddress string

		resp, httpRes, err := apiClient.EmailInfoAPI.GetEmailAddressInfo(context.Background(), emailAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailInfoAPIService GetEmailCSV", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailInfoAPI.GetEmailCSV(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
