/*
api.emaildetective.io API

EmailDetective.io is an API focusing on validating email addresses and providing a score based off how suspicious an email address is.  To get started register a new user (make sure to verify your email) and then you can can start getting email information.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaildetective

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkEmailInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkEmailInfoRequest{}

// BulkEmailInfoRequest struct for BulkEmailInfoRequest
type BulkEmailInfoRequest struct {
	Data []string `json:"data"`
}

type _BulkEmailInfoRequest BulkEmailInfoRequest

// NewBulkEmailInfoRequest instantiates a new BulkEmailInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkEmailInfoRequest(data []string) *BulkEmailInfoRequest {
	this := BulkEmailInfoRequest{}
	this.Data = data
	return &this
}

// NewBulkEmailInfoRequestWithDefaults instantiates a new BulkEmailInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkEmailInfoRequestWithDefaults() *BulkEmailInfoRequest {
	this := BulkEmailInfoRequest{}
	return &this
}

// GetData returns the Data field value
func (o *BulkEmailInfoRequest) GetData() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BulkEmailInfoRequest) GetDataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BulkEmailInfoRequest) SetData(v []string) {
	o.Data = v
}

func (o BulkEmailInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkEmailInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BulkEmailInfoRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkEmailInfoRequest := _BulkEmailInfoRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkEmailInfoRequest)

	if err != nil {
		return err
	}

	*o = BulkEmailInfoRequest(varBulkEmailInfoRequest)

	return err
}

type NullableBulkEmailInfoRequest struct {
	value *BulkEmailInfoRequest
	isSet bool
}

func (v NullableBulkEmailInfoRequest) Get() *BulkEmailInfoRequest {
	return v.value
}

func (v *NullableBulkEmailInfoRequest) Set(val *BulkEmailInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkEmailInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkEmailInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkEmailInfoRequest(val *BulkEmailInfoRequest) *NullableBulkEmailInfoRequest {
	return &NullableBulkEmailInfoRequest{value: val, isSet: true}
}

func (v NullableBulkEmailInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkEmailInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


