/*
api.emaildetective.io API

EmailDetective.io is an API focusing on validating email addresses and providing a score based off how suspicious an email address is.  To get started register a new user (make sure to verify your email) and then you can can start getting email information.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaildetective

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkEmailInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkEmailInfoResponse{}

// BulkEmailInfoResponse struct for BulkEmailInfoResponse
type BulkEmailInfoResponse struct {
	Data []EmailInfoResponse `json:"data"`
}

type _BulkEmailInfoResponse BulkEmailInfoResponse

// NewBulkEmailInfoResponse instantiates a new BulkEmailInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkEmailInfoResponse(data []EmailInfoResponse) *BulkEmailInfoResponse {
	this := BulkEmailInfoResponse{}
	this.Data = data
	return &this
}

// NewBulkEmailInfoResponseWithDefaults instantiates a new BulkEmailInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkEmailInfoResponseWithDefaults() *BulkEmailInfoResponse {
	this := BulkEmailInfoResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BulkEmailInfoResponse) GetData() []EmailInfoResponse {
	if o == nil {
		var ret []EmailInfoResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BulkEmailInfoResponse) GetDataOk() ([]EmailInfoResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BulkEmailInfoResponse) SetData(v []EmailInfoResponse) {
	o.Data = v
}

func (o BulkEmailInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkEmailInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BulkEmailInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkEmailInfoResponse := _BulkEmailInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkEmailInfoResponse)

	if err != nil {
		return err
	}

	*o = BulkEmailInfoResponse(varBulkEmailInfoResponse)

	return err
}

type NullableBulkEmailInfoResponse struct {
	value *BulkEmailInfoResponse
	isSet bool
}

func (v NullableBulkEmailInfoResponse) Get() *BulkEmailInfoResponse {
	return v.value
}

func (v *NullableBulkEmailInfoResponse) Set(val *BulkEmailInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkEmailInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkEmailInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkEmailInfoResponse(val *BulkEmailInfoResponse) *NullableBulkEmailInfoResponse {
	return &NullableBulkEmailInfoResponse{value: val, isSet: true}
}

func (v NullableBulkEmailInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkEmailInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


